# Generated by Django 4.0.4 on 2026-03-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0005_questions_dependency_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='dependency_rule',
            field=models.CharField(
                blank=True,
                choices=[('AND', 'AND'), ('OR', 'OR')],
                help_text='Dependency evaluation rule: AND or OR. Defaults to AND in client logic if not specified.',
                max_length=3,
                null=True),
        ),
    ]
