name: 'Install GKE Auth Plugin Action'
description: 'Install GKE Auth Plugin Action'
runs:
  using: "composite"
  steps:
    - run: |
        set -euo pipefail
        REPO_URL="https://packages.cloud.google.com/apt"

        # Install the Google Cloud SDK
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] $REPO_URL cloud-sdk main" | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list
        curl -fsSL "$REPO_URL/doc/apt-key.gpg" | sudo gpg --dearmor --yes -o /usr/share/keyrings/cloud.google.gpg
        sudo apt-get update -y
        sudo apt-get install -y google-cloud-cli-gke-gcloud-auth-plugin
      shell: bash